### ISSUE TITLE
Error’s upon errors….

### ISSUE THREAD

**Issue by Cszura** [Nookbot/Nookbot#41]
Hello I’ve filled out the following config went over the code edited it as I need no errors there loads all commands but getting an error when It try’s to fetch the reaction modules! You can see the full error in the Image Below! Hope you can find a solve for my issue!
![IMG_1590](https://user-images.githubusercontent.com/81977221/123118312-84f2c500-d410-11eb-8f83-525cc90f733d.jpeg)

**Comment by Phoenix1128** [comment]
Ensure you have [src/modules/fetchReactionModules.js](https://github.com/Nookbot/Nookbot/blob/develop/src/modules/fetchReactionModules.js) or just remove that line from ready.js.

**Comment by Cszura** [comment]
Thank you! That solved that issue but now.. When I try to run a command I get this error 
`(node:185) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at module.exports (/home/runner/Tom-Nook-Bot/events/message.js:183:58)
    at Client.emit (events.js:314:20)
    at Client.EventEmitter.emit (domain.js:483:12)
    at MessageCreateAction.handle (/home/runner/Tom-Nook-Bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Tom-Nook-Bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Tom-Nook-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/Tom-Nook-Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/Tom-Nook-Bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/runner/Tom-Nook-Bot/node_modules/ws/lib/event-target.js:132:16)`

**Comment by Phoenix1128** [comment]
You'll need to provide more information on the line the error was caught on (line 183 of message.js).

**Comment by Cszura** [comment]
Here’s line 183 `    if (message.guild && client.config.imageOnlyChannels.includes(message.channel.id) `

**Comment by Phoenix1128** [comment]
Ensure you have the `imageOnlyChannels` property in `config.js`. The error says it cannot run the includes method on an undefined property so it must be defined.

**Comment by Cszura** [comment]
Your gonna hate me but I’m getting an error again👁👄👁
![IMG_1597](https://user-images.githubusercontent.com/81977221/124044259-03380400-d9db-11eb-9fc5-6f33a552a199.jpeg)

**Comment by Phoenix1128** [comment]
A lot of features in Nookbot, actually all of them, were made specifically for the ACNH server so a lot of configuration and changes would be necessary for the bot to function properly. The wiki has not been updated in a while and has some outdated information because of some newer features. I, unfortunately, don't have the time to go through and help you configure the bot exactly. I'd recommend learning Javascript and how to read errors if you wish to have a working process.

**Comment by Cszura** [comment]
Ah okay thanks for the help!
